Add unreasonably unkempt commit before leaving for vacation

diff --git a/assets/common b/assets/common
--- a/assets/common
+++ b/assets/common
@@ -1,6 +1,29 @@
+#!/usr/bin/env bash
+
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 NC='\033[0m'
+
+CURL_INSECURE="${CURL_INSECURE:=false}"
+CURL_RETRY="${CURL_RETRY:=true}"
+
+curl_options=("--fail")
+
+if [[ ${CURL_INSECURE} = "true" ]]; then curl_options+=("--insecure"); fi
+if [[ ${CURL_RETRY} = "true" ]]; then
+  CURL_RETRY_NUM="${CURL_RETRY_NUM:=5}"
+  curl_options+=("--retry" "${CURL_RETRY_NUM}")
+  curl_options+=("--retry-connrefused")
+fi
+
+log() {
+    echo "$@" >&2
+}
+
+log_fatal() {
+    log -e "${RED}" "$@" "${NC}"
+    exit 1
+}
 
 strip_last_slash() {
     path=${1}
@@ -29,11 +52,10 @@ get_version() {
         return 1
     fi
 
-    version=$(cat ${destination}/${version_file} | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
+    version=$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' "${destination}/${version_file}")
 
-    if [[ -z "${version}" ]]; then
-        echo "version is undefined" >&2
-        return 1
+    if [[ -z ${version} ]]; then
+        log_fatal "version is undefined"
     fi
 
     echo "${version}"
@@ -44,9 +66,8 @@ is_valid() {
     field_name=${1}
     field_value=${2}
 
-    if [ -z "${field_value}" ]; then
-        echo "invalid source (missing ${field_name})" >&2
-        exit 1
+    if [[ -z ${field_value} ]]; then
+        log_fatal "invalid source (missing ${field_name})" >&2
     fi
 }
 
@@ -60,10 +81,10 @@ is_file_complies_with_artifact_specs() {
     regex="^(${forward}|${backward})"
 
     if grep -qvE "${regex}" <<< "${file}"; then
-        echo -e "artifact ${RED}${file}${NC} does not comply with artifact source specs" >&2
-        echo -e "Supported specs are :" >&2
-        echo -e "  - ${GREEN}${artifact_id}-${version}[-classifier].packaging${NC})" >&2
-        echo -e "  - ${GREEN}${artifact_id}-[classifier-]${version}.packaging${NC})" >&2
+        log -e "artifact ${RED}${file}${NC} does not comply with artifact source specs"
+        log -e "Supported specs are :"
+        log -e "  - ${GREEN}${artifact_id}-${version}[-classifier].packaging${NC})"
+        log -e "  - ${GREEN}${artifact_id}[-classifier]-${version}.packaging${NC})"
         exit 1
     fi
 }
@@ -71,17 +92,17 @@ is_file_complies_with_artifact_specs() {
 get_latest_version() {
     payload=${1}
 
-    api_key=$(jq -r '.source.api_key // ""' < ${payload})
-    repository_id=$(jq -r '.source.repository_id // ""' < ${payload})
-    group_id=$(jq -r '.source.group_id // ""' < ${payload})
-    artifact_id=$(jq -r '.source.artifact_id // ""' < ${payload})
-    host=$(jq -r '.source.host // ""' < ${payload})
+    api_key="$(jq -r '.source.api_key // ""' < ${payload})"
+    repository_id="$(jq -r '.source.repository_id // ""' < ${payload})"
+    group_id="$(jq -r '.source.group_id // ""' < ${payload})"
+    artifact_id="$(jq -r '.source.artifact_id // ""' < ${payload})"
+    host="$(jq -r '.source.host // ""' < ${payload})"
 
-    is_valid 'api_key' ${api_key}
-    is_valid 'repository_id' ${repository_id}
-    is_valid 'group_id' ${group_id}
-    is_valid 'artifact_id' ${artifact_id}
-    is_valid 'host' ${host}
+    is_valid 'api_key' "${api_key}"
+    is_valid 'repository_id' "${repository_id}"
+    is_valid 'group_id' "${group_id}"
+    is_valid 'artifact_id' "${artifact_id}"
+    is_valid 'host' "${host}"
 
     lastest_version=''
 
@@ -93,25 +114,25 @@ get_latest_version() {
         {\"path\": \"${group_id_path}/${artifact_id}\"}
     ).include(\"repo\",\"name\",\"path\")"
 
-    result_folder=$(curl \
-        -k \
+    result_folder="$(curl \
+        "${curl_options[@]}" \
         -X POST \
         -H "X-JFrog-Art-Api:${api_key}" \
         -H "Content-Type:text/plain" \
         -d "${aql_folder}" \
         --write-out "\n%{http_code}" \
         --silent \
-        ${host}/api/search/aql)
+        "${host}/api/search/aql")"
   
     http_code="${result_folder##*$'\n'}"
-    req_folder=$(echo "${result_folder}" | sed '$d')
+    req_folder="$(echo "${result_folder}" | sed '$d')"
 
     if [[ ${http_code} -eq '200' ]]; then
-        lastest_version=$(echo ${req_folder} | jq -r '[.results[].name|{timestamp: split("-")[0]|split(".")|map(.|tonumber), ref: .}]|sort_by(.ref)|last.ref')
+        lastest_version="$( jq -r '[ .results[].name | { timestamp: split("-")[0] | split(".") | map( . | tonumber ), ref: . } ] | sort_by(.ref) | last.ref' <<< "${req_folder}" )"
     else
-        echo "Unable to retreive folder in artifactory (get_latest_version)" >&2
-        echo "Request: curl -k -X POST -H 'X-JFrog-Art-Api:*****' -H 'Content-Type:text/plain' -d "${aql_folder}" --write-out "\n%{http_code}" --silent ${host}/api/search/aql" >&2
-        echo "Error: ${req_folder}" >&2
+        log "Unable to retreive folder in artifactory (get_latest_version)"
+        log "Request: curl ${curl_options[*]} -X POST -H 'X-JFrog-Art-Api:*****' -H 'Content-Type:text/plain' -d ${aql_folder} --write-out "\n%{http_code}" --silent ${host}/api/search/aql"
+        log "Error: ${req_folder}"
         return 1
     fi
 
@@ -124,17 +145,17 @@ folder_metadata() {
     destination=${2}
     version=${3}
 
-    api_key=$(jq -r '.source.api_key // ""' < ${payload})
-    repository_id=$(jq -r '.source.repository_id // ""' < ${payload})
-    group_id=$(jq -r '.source.group_id // ""' < ${payload})
-    artifact_id=$(jq -r '.source.artifact_id // ""' < ${payload})
-    host=$(jq -r '.source.host // ""' < ${payload})
+    api_key="$(jq -r '.source.api_key // ""' < "${payload}")"
+    repository_id="$(jq -r '.source.repository_id // ""' < "${payload}")"
+    group_id="$(jq -r '.source.group_id // ""' < "${payload}")"
+    artifact_id="$(jq -r '.source.artifact_id // ""' < "${payload}")"
+    host="$(jq -r '.source.host // ""' < "${payload}")"
 
-    is_valid 'api_key' ${api_key}
-    is_valid 'repository_id' ${repository_id}
-    is_valid 'group_id' ${group_id}
-    is_valid 'artifact_id' ${artifact_id}
-    is_valid 'host' ${host}
+    is_valid 'api_key' "${api_key}"
+    is_valid 'repository_id' "${repository_id}"
+    is_valid 'group_id' "${group_id}"
+    is_valid 'artifact_id' "${artifact_id}"
+    is_valid 'host' "${host}"
 
     metadata_folder='[]'
 
@@ -156,24 +177,24 @@ folder_metadata() {
     )"
 
     result_folder=$(curl \
-        -k \
+        "${curl_options[@]}" \
         -X POST \
         -H "X-JFrog-Art-Api:${api_key}" \
         -H "Content-Type:text/plain" \
         -d "${aql_folder}" \
         --write-out "\n%{http_code}" \
         --silent \
-        ${host}/api/search/aql)
+        "${host}/api/search/aql")
   
     http_code="${result_folder##*$'\n'}"
     req_folder=$(echo "${result_folder}" | sed '$d')
 
     if [[ ${http_code} -eq '200' ]]; then
-        metadata_folder=$(echo ${req_folder} | jq '[.results[]|del(.type,.size)|to_entries[]|{name: .key, value}]')
+        metadata_folder=$( jq '[ .results[] | del( .type, .size ) | to_entries[] | { name: .key, value } ]' <<< "${req_folder}" )
     else
-        echo "Unable to retreive files in artifactory" >&2
-        echo "Request: curl -k -X POST -H 'X-JFrog-Art-Api:*****' -H 'Content-Type:text/plain' -d "${aql_folder}" --write-out "\n%{http_code}" --silent ${host}/api/search/aql" >&2
-        echo "Error: ${req_folder}" >&2
+        log "Unable to retreive files in artifactory"
+        log "Request: curl ${curl_options[*]} -X POST -H 'X-JFrog-Art-Api:*****' -H 'Content-Type:text/plain' -d ${aql_folder} --write-out "\n%{http_code}" --silent ${host}/api/search/aql"
+        log "Error: ${req_folder}"
         return 1
     fi
 
